### PR TITLE
spiffe csi volume for oidc

### PR DESCRIPTION
**Pull request by marcofranssen**
- Utilize spiffe csi driver in OIDC component
- Align spire-server sock naming convention with agent

### CODE REVIEW

**Review by gjkamstra — CHANGES_REQUESTED** [review]
Looks good, 
Please also update the example in charts/spire-client-example/templates/client-deployment.yaml L54
and the NOTES: charts/spire-client-example/templates/NOTES.txt L4

**Comment by marcofranssen** [comment]
> Looks good,
> Please also update the example in charts/spire-client-example/templates/client-deployment.yaml L54
> and the NOTES: charts/spire-client-example/templates/NOTES.txt L4

This is part of a different helm chart. Our ci pipeline can only handle one chart per PR. Will update the example as well.

**Comment by marcofranssen** [comment]
See #72 for the update of the example.

**Review by gjkamstra — APPROVED** [review]
LGTM

**Pull request merged**
